#spring:
#  application:
#    name: miki7
#  datasource:
#    url: jdbc:mysql://localhost:3306/mikidb?serverTimezone=UTC&useSSL=false
#    username: root
#    password: mysql
##    password : 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
